FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY core/recommender_api.py .

CMD ["sh", "-c", "uvicorn recommender_api:app --host 0.0.0.0 --port $PORT"]