"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (MUST be after BASE_DIR is defined)
# .env file should be in the same directory as manage.py (core/ directory)
dotenv_path = BASE_DIR / '.env'
load_dotenv(dotenv_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j^mre+-0a*p$2hjar=pt*muzsh0w^f(zhh2z8g1c41@-$_+v(#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]


# Authentication settings
AUTH_USER_MODEL = 'users.CustomUser'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',

    'core.users',
    'core.courses',
    'core.recommender',
]

from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import os

mongo_uri = os.getenv("MONGO_URI")

if not mongo_uri:
    raise Exception("MONGO_URI not set in environment variables")

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': os.getenv('MONGO_DB_NAME', 'learnsmart_db'),
        'ENFORCE_SCHEMA': False,
        'CLIENT': {
            'host': mongo_uri
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Authentication
LOGIN_REDIRECT_URL = '/recommend/'
LOGIN_URL = '/accounts/login/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ═══════════════════════════════════════════════════════════════════════════════
#  REAL API KEYS — For personalized course recommendations and AI roadmap generation
# ═══════════════════════════════════════════════════════════════════════════════
# Load from .env file. If not set, these will be empty strings (use mock data instead)

# YOUTUBE DATA API v3
# Get key: https://console.cloud.google.com
# Steps: New Project → Enable "YouTube Data API v3" → Credentials → Create API Key
# Set in .env as: YOUTUBE_API_KEY=your_key_here
# Default to the provided key if the environment variable is not set
YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY", "AIzaSyA9ygp0M9fMXO2xis1n9wnyykwPp-gJLkQ")

# UDEMY AFFILIATE API
# Get keys: https://www.udemy.com/developers/affiliate/
# Steps: Log in → Request Affiliate Access → Copy Client ID & Secret
# Set in .env as: UDEMY_CLIENT_ID=your_id and UDEMY_CLIENT_SECRET=your_secret
UDEMY_CLIENT_ID = os.getenv("UDEMY_CLIENT_ID", "")
UDEMY_CLIENT_SECRET = os.getenv("UDEMY_CLIENT_SECRET", "")

# ANTHROPIC CLAUDE AI (for AI-powered roadmap generation)
# Get key: https://console.anthropic.com
# Steps: Sign up → API Keys → Create Key
# Set in .env as: ANTHROPIC_API_KEY=your_key_here
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")

# Note: Coursera API was removed due to 405 errors in deprecated backend

# Coursera API endpoint (public catalog)
# Set in .env as: COURSERA_API_URL=https://api.coursera.org/api/courses.v1
COURSERA_API_URL = os.getenv("COURSERA_API_URL", "https://api.coursera.org/api/courses.v1?limit=20")



SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Fix Railway / HTTPS / iframe issues
CSRF_TRUSTED_ORIGINS = [
    "https://learnsmart-django-production.up.railway.app"
]

X_FRAME_OPTIONS = "ALLOWALL"

SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True