# Generated by Django 6.0.1 on 2026-02-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=50)),
                ('skill_tags', models.TextField()),
                ('difficulty', models.CharField(max_length=50)),
            ],
        ),
    ]
